name: Build Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Change config.js file for testing
      run: echo "export const settings = { host:\"http://localhost:3030\"};" > src/config.js
    - name: Start Backend
      run: npm run server &
    - name: Start Frontend
      run: npm run start &
    - name: Install Playwright library 
      run: npx playwright install
    - name: Start UI tests
      run: npm run test
